version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /client/node_modules
    environment:
      - VUE_APP_NODE_API_URL=api

  api:
    container_name: api
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=development
    links:
      - mongo

  nginx:
    container_name: router
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "1337:7888"
