name: Deploy to Staging

on: workflow_dispatch

jobs:
  api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Checkout Github"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Push to dockerhub"
        run: |
          docker build -t ${ DOCKER_REGISTRY }/example-app-api ./api
          docker push ${ DOCKER_REGISTRY }/example-app-api

  client-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Checkout Github"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Push to dockerhub"
        run: |
          docker build -t ${ DOCKERHUB_USERNAME }/example-app-client ./client
          docker push ${ DOCKERHUB_USERNAME }/example-app-client

  router-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Checkout Github"
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: "Push to dockerhub"
        run: |
          docker build -t ${ DOCKER_REGISTRY }/example-app-router ./router
          docker push ${ DOCKER_REGISTRY }/example-app-router
  # push-to-staging:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{ secrets.DOCKER_REGISTRY }}
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #     - name: "Checkout Github"
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: "true"
