name: Deploy to Staging

on: workflow_dispatch

jobs:
  push-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Github"
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Login to Azure registry"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build containers and push to registry"
        run: |
          docker-compose -f production.yml build
          docker-compose push

      - name: "Deploy to Azure Container Instances"
        uses: "azure/aci-deploy@v1"
        with:
          resource-group: jr98resourceGroup
          dns-name-label: example-client-app
          registry-login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          image: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/${{  github.event.repository.name }}:${{ github.sha }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: ${{  github.event.repository.name }}-container
          location: "uksouth"
