name: Deploy to Staging

on: workflow_dispatch

jobs:
  api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Checkout Github"
        uses: Mushus/checkout-submodule@v1
        with:
          submodulePath: ./api
      - name: "Push to dockerhub"
        run: |
          docker build -t ${ DOCKER_REGISTRY }/example-app-api
          docker push ${ DOCKER_REGISTRY }/example-app-api

  client-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Checkout Github"
        uses: Mushus/checkout-submodule@v1
        with:
          submodulePath: ./client
      - name: "Push to dockerhub"
        run: |
          docker build -t ${ DOCKER_REGISTRY }/example-app-client
          docker push ${ DOCKER_REGISTRY }/example-app-client

  router-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "Checkout Github"
        uses: Mushus/checkout-submodule@v1
        with:
          submodulePath: ./router
      - name: "Push to dockerhub"
        run: |
          docker build -t ${ DOCKER_REGISTRY }/example-app-router
          docker push ${ DOCKER_REGISTRY }/example-app-router
  # push-to-staging:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{ secrets.DOCKER_REGISTRY }}
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #     - name: "Checkout Github"
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: "true"
